### ISSUE TITLE
page50,cat flights.csv | ./mapper.py | sort | ./reducer.py does not work

### ISSUE THREAD

**Issue by Alxe1** [bbengfort/hadoop-fundamentals#10]
I use cat flights.csv | ./mapper.py | sort | ./reducer.py to run, but it shows : No such file or directory
: No such file or directory. But it is really in the working directory and they are executable. What is wrong?

**Comment by bbengfort** [comment]
Can you do an `ls -la` on the directory you're working in? I suspect that the `mapper.py` and `reducer.py` may not be executable. (e.g. don't have perms that look something like `-rwxr--r--` (note the first x). If not you can fix it with `chmod +x mapper.py` and do the same for `reducer.py`. Let me know if that helps, and the contents of `ls -la` if not.

**Comment by Alxe1** [comment]
thank you, have done!
