### ISSUE TITLE
cat flights-Apr2014.csv | ./mapper.py | sort | ./reducer.py > output.txt

### ISSUE THREAD

**Issue by doremoteph7** [bbengfort/hadoop-fundamentals#16]
Hi Benjamin,

Trying to follow the video where the following command was used:
cat flights-Apr2014.csv | ./mapper.py | sort | ./reducer.py > output.txt

Is it accurate that we should use the file from the github path data/flight_data.zip, file name ontime_flights.tsv? Not sure if tsv and csv file format is the cause for the error encountered.

Currently getting the error message : 
IndexError: list index out of range
File "./mapper.py", line 20, in map
   self.emit(row[14], row[31])

Can point out which mapper.py file and which input file (csv or tsv) should we use? :)

**Comment by bbengfort** [comment]
Hi @doremoteph7 perhaps try the CSV file in `data/ontime.zip`? I think this is the dataset that was used in the `avgdelay` code snippets.
