### ISSUE TITLE
Ch6v2: video/audio unsynchronized

### ISSUE THREAD

**Issue by ghost** [bbengfort/hadoop-fundamentals#5]
Chapter 6, video 2 (Linear Regression), at 1:39 the audio stops in the middle of Ben speaking, then the audio track starts over at the beginning again at 1:43 on the video clock. The rest of the video is the out of sync.

**Comment by bbengfort** [comment]
@jdgehman I've forwarded your note to the tools team at O'Reilly; though I think they might be on travel. I'll let you know how they respond about the fixes. Thanks for letting us know!

**Comment by bbengfort** [comment]
@jdgehman The tools team reviewed the video and found no video/audio sync issues. Perhaps your download got mangled some how? If you're able to retry the download, I'd suggest it. Otherwise, I'll get a contact at O'Reilly who will be able to assist you.

**Comment by bbengfort** [comment]
@jdgehman -- let me know if you need any assistance from O'Reilly! I just realized closing the issue may have stopped comments; so I've reopened it.

**Comment by ghost** [comment]
Thanks @bbengfort. Unfortunately I couldn't download from outside the U.S., so I had to pay a bomb to ship the DVD via a forwarding service (apparently Hadoop training is a national security risk). I'd copied the DVD to my hard drive -- it's this copy that gives me the problem, both in compatibility mode under ubuntu (as well as mplayer on the mp4 file) and via the windows player on Windows 10 on VirtualBox. I haven't had a chance yet to check playing directly off of the DVD. Nevertheless, is it possible O'Reilly only checked the download version and not the DVD version I would have received?
