### ISSUE TITLE
avgdelay folder does not match up with the videos

### ISSUE THREAD

**Issue by ghost** [bbengfort/hadoop-fundamentals#6]
Hey all,

following through with your course and noticed that the /avgdelay/flights_per_day_january directory just includes copies of the mapper.py and reducer.py code, not the flights-Apr2014.csv file, which is not in the data/flight_data.zip file either.  Am I missing something?

**Comment by bbengfort** [comment]
@krautt sorry about that, the download from RITA kept changing out from under us after the video was released. I'm pretty sure if you use the mapper and reducer in that folder with the flights.tsv data it should work - did you try it?

**Comment by ghost** [comment]
Thanks @bbengfort , sorry for delay, I _believe_ that i did try that if I recall correctly. I don't think the file formats were similar.  At this point I've moved on to your sales.py app in the pyspark section.  had some issues with that too that i submitted to the issues page.  BTW, what's RITA?

**Comment by bbengfort** [comment]
[RITA](http://www.rita.dot.gov/) is the research and technology arm of the U.S. Department of Transportation; they're the ones that provided the data set we're using.
