### ISSUE TITLE
Hadoop install instructions have -R out of place

### ISSUE THREAD

**Issue by davidrath** [bbengfort/hadoop-fundamentals#8]
You probably have already discovered this, but just in case, I wanted to let you know that the recursive switch '-R' is out of sequence in a couple of your install commands in the Appendix.  On page 231 you have the first one right:

'sudo shown -R hadoop:hadoop /srv/hadoop-2.5.0', but the next one 
'sudo chmod g+w -R /srv/hadoop-2.5.0' fails because the options ('-R) needs to come before the mode (g+w).

The same thing is true on page 234.  Not a big deal, but it might frustrate someone not familiar with Unix.

**Comment by bbengfort** [comment]
@davidrath thanks for the note; I'll see if we can update the errata in the book to mention this in case anyone else is having trouble.
