### ISSUE TITLE
Where is 'WordCount.java' code for Data Analytics with Hadoop book?

### ISSUE THREAD

**Issue by davidrath** [bbengfort/hadoop-fundamentals#9]
I'm following along in the Data Analytics with Hadoop book, and I can't seem to find the 'WordCount.zip' file for the java code.  I could find some python code with the same name but I don't think that's it.  Please let me know where I can find the java source.  Thanks.

**Comment by gchadder3** [comment]
I also cannot find WordCount.zip, and I tried looking in a few earlier commits of the repo.

**Comment by bbengfort** [comment]
@davidrath @gchadder3 -- well, it was removed for some reason, and I'm not 100% sure why. I've added it back to the Repo in the [wordcount](https://github.com/bbengfort/hadoop-fundamentals/tree/master/wordcount) folder.

I'd appreciate it if you guys could try it out and let me know if it works; there might have been a Java 8/Hadoop Framework version change that caused us to remove it. If it doesn't work, let me know what you're running on and I'll see if I can spin it up.

**Comment by davidrath** [comment]
I found the zip file okay now.

However, when I tried to run

```
“hadoop com.sun.tools.javac.Main WordCount.java”
```

 (page 39), it choked with the error

```
"Error: Could not find or load main class com.sun.tools.javac.Main”
```

My config is:
Mac OSX vers 10.11.6
Java 1.8.101
Hadoop 2.6.4

A simple javac couldn’t resolve all of the package details.  🤔

**Comment by gchadder3** [comment]
I was able to get the code to work on the IBM Demo Cloud, which is running under Linux, Java 1.8.0_71, and Hadoop 2.7.1-IBM-8.  However, I had to use some commands different than what was in the Data Analytics with Hadoop book to get it to compile and run:

javac -cp `hadoop classpath` *.java
compiled the Java source code in class files.

jar cf wc.jar *.class
compiled the JAR file.

Then you have to copy wc.jar outside the directory with the .class files and run the next command there, or you get errors from not finding the classes.

hadoop jar ./wc.jar WordCount shakespeare.txt wordcounts
finally runs the job on the Shakespeare data, and it completes in a few seconds.

**Comment by bbengfort** [comment]
@davidrath make sure that hadoop knows your `$JAVA_HOME` by adding that environment variable to the hadoop environment scripts. Alternatively you can specify the classpath using the `-classpath` option.

See [http://stackoverflow.com/questions/26793847/main-class-not-found-when-compiling-hadoop-sample-program](http://stackoverflow.com/questions/26793847/main-class-not-found-when-compiling-hadoop-sample-program) for more information on how to compile Java programs on the command line with Hadoop. 

@gchadder3 Glad you figured it out from the reverse direction, using `javac` and specifying the Hadoop class path. 

For both of you guys, the focus of the book is on using Python with Hadoop - you shouldn't have to deal with compiling any Java from here on out. If you're interested in writing Java MapReduce programs, I highly recommend Tom White's book. The normal workflow for Java, though, is not necessarily compiling  MapReduce programs on the command line like you might do with Python, but instead working with Maven in an IDE, compiling to a JAR then submitting that JAR to the cluster. So hopefully you won't have to go through this process on a routine basis!
